name: neovim arm64 release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
jobs:
  release:
    name: Release neovim arm64 with docker
    runs-on: ubuntu-latest
    outputs:
      nvim_version: ${{ steps.set_nvim_version.outputs.nvim_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get nvim version
        id: set_nvim_version
        run: |
          nvim_version="${{ github.ref_name }}"
          echo "nvim_version=${nvim_version%-[0-9]}" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          build-args: BRANCH=${{ steps.set_nvim_version.outputs.nvim_version }}
          outputs: type=local,dest=.
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Rename
        run: set -x; mv nvim.appimage nvim.${{ steps.set_nvim_version.outputs.nvim_version }}.arm64.appimage
      - name: Release
        # uses: https://gitea.com/actions/gitea-release-action@v1
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nvim.${{ steps.set_nvim_version.outputs.nvim_version }}.arm64.appimage
